version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mammo-frontend-client
    network_mode: host
    command: sh -c "npm run build && npm run preview -- --host --port 4173"
    environment:
      - HOST=0.0.0.0
