# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import world_pb2 as world__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in world_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorldStub(object):
    """The World service provides information about the world.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeIndexer = channel.unary_stream(
                '/world.World/SubscribeIndexer',
                request_serializer=world__pb2.SubscribeIndexerRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeIndexerResponse.FromString,
                _registered_method=True)
        self.WorldMetadata = channel.unary_unary(
                '/world.World/WorldMetadata',
                request_serializer=world__pb2.WorldMetadataRequest.SerializeToString,
                response_deserializer=world__pb2.WorldMetadataResponse.FromString,
                _registered_method=True)
        self.SubscribeModels = channel.unary_stream(
                '/world.World/SubscribeModels',
                request_serializer=world__pb2.SubscribeModelsRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeModelsResponse.FromString,
                _registered_method=True)
        self.SubscribeEntities = channel.unary_stream(
                '/world.World/SubscribeEntities',
                request_serializer=world__pb2.SubscribeEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeEntityResponse.FromString,
                _registered_method=True)
        self.UpdateEntitiesSubscription = channel.unary_unary(
                '/world.World/UpdateEntitiesSubscription',
                request_serializer=world__pb2.UpdateEntitiesSubscriptionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RetrieveEntities = channel.unary_unary(
                '/world.World/RetrieveEntities',
                request_serializer=world__pb2.RetrieveEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveEntitiesResponse.FromString,
                _registered_method=True)
        self.RetrieveEntitiesStreaming = channel.unary_stream(
                '/world.World/RetrieveEntitiesStreaming',
                request_serializer=world__pb2.RetrieveEntitiesRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveEntitiesStreamingResponse.FromString,
                _registered_method=True)
        self.SubscribeEventMessages = channel.unary_stream(
                '/world.World/SubscribeEventMessages',
                request_serializer=world__pb2.SubscribeEventMessagesRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeEntityResponse.FromString,
                _registered_method=True)
        self.UpdateEventMessagesSubscription = channel.unary_unary(
                '/world.World/UpdateEventMessagesSubscription',
                request_serializer=world__pb2.UpdateEventMessagesSubscriptionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeTokenBalances = channel.unary_stream(
                '/world.World/SubscribeTokenBalances',
                request_serializer=world__pb2.RetrieveTokenBalancesRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeTokenBalancesResponse.FromString,
                _registered_method=True)
        self.UpdateTokenBalancesSubscription = channel.unary_unary(
                '/world.World/UpdateTokenBalancesSubscription',
                request_serializer=world__pb2.UpdateTokenBalancesSubscriptionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeTokens = channel.unary_stream(
                '/world.World/SubscribeTokens',
                request_serializer=world__pb2.RetrieveTokensRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeTokensResponse.FromString,
                _registered_method=True)
        self.UpdateTokensSubscription = channel.unary_unary(
                '/world.World/UpdateTokensSubscription',
                request_serializer=world__pb2.UpdateTokenSubscriptionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RetrieveEventMessages = channel.unary_unary(
                '/world.World/RetrieveEventMessages',
                request_serializer=world__pb2.RetrieveEventMessagesRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveEntitiesResponse.FromString,
                _registered_method=True)
        self.RetrieveEvents = channel.unary_unary(
                '/world.World/RetrieveEvents',
                request_serializer=world__pb2.RetrieveEventsRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveEventsResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/world.World/SubscribeEvents',
                request_serializer=world__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=world__pb2.SubscribeEventsResponse.FromString,
                _registered_method=True)
        self.RetrieveTokens = channel.unary_unary(
                '/world.World/RetrieveTokens',
                request_serializer=world__pb2.RetrieveTokensRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveTokensResponse.FromString,
                _registered_method=True)
        self.RetrieveTokenBalances = channel.unary_unary(
                '/world.World/RetrieveTokenBalances',
                request_serializer=world__pb2.RetrieveTokenBalancesRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveTokenBalancesResponse.FromString,
                _registered_method=True)
        self.RetrieveControllers = channel.unary_unary(
                '/world.World/RetrieveControllers',
                request_serializer=world__pb2.RetrieveControllersRequest.SerializeToString,
                response_deserializer=world__pb2.RetrieveControllersResponse.FromString,
                _registered_method=True)


class WorldServicer(object):
    """The World service provides information about the world.
    """

    def SubscribeIndexer(self, request, context):
        """Subscribes to updates about the indexer. Like the head block number, tps, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorldMetadata(self, request, context):
        """Retrieves metadata about the World including all the registered components and systems.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeModels(self, request, context):
        """Subscribes to models updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEntities(self, request, context):
        """Subscribe to entity updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntitiesSubscription(self, request, context):
        """Update entity subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveEntities(self, request, context):
        """Retrieve entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveEntitiesStreaming(self, request, context):
        """Retrieve entities as a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEventMessages(self, request, context):
        """Subscribe to entity updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEventMessagesSubscription(self, request, context):
        """Update entity subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTokenBalances(self, request, context):
        """Subscribe to token balance updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTokenBalancesSubscription(self, request, context):
        """Update token balance subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTokens(self, request, context):
        """Subscribe to token updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTokensSubscription(self, request, context):
        """Update token subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveEventMessages(self, request, context):
        """Retrieve entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveEvents(self, request, context):
        """Retrieve events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveTokens(self, request, context):
        """Retrieve tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveTokenBalances(self, request, context):
        """Retrieve token balances
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveControllers(self, request, context):
        """Retrieve controllers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeIndexer': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeIndexer,
                    request_deserializer=world__pb2.SubscribeIndexerRequest.FromString,
                    response_serializer=world__pb2.SubscribeIndexerResponse.SerializeToString,
            ),
            'WorldMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.WorldMetadata,
                    request_deserializer=world__pb2.WorldMetadataRequest.FromString,
                    response_serializer=world__pb2.WorldMetadataResponse.SerializeToString,
            ),
            'SubscribeModels': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeModels,
                    request_deserializer=world__pb2.SubscribeModelsRequest.FromString,
                    response_serializer=world__pb2.SubscribeModelsResponse.SerializeToString,
            ),
            'SubscribeEntities': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEntities,
                    request_deserializer=world__pb2.SubscribeEntitiesRequest.FromString,
                    response_serializer=world__pb2.SubscribeEntityResponse.SerializeToString,
            ),
            'UpdateEntitiesSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntitiesSubscription,
                    request_deserializer=world__pb2.UpdateEntitiesSubscriptionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RetrieveEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveEntities,
                    request_deserializer=world__pb2.RetrieveEntitiesRequest.FromString,
                    response_serializer=world__pb2.RetrieveEntitiesResponse.SerializeToString,
            ),
            'RetrieveEntitiesStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveEntitiesStreaming,
                    request_deserializer=world__pb2.RetrieveEntitiesRequest.FromString,
                    response_serializer=world__pb2.RetrieveEntitiesStreamingResponse.SerializeToString,
            ),
            'SubscribeEventMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEventMessages,
                    request_deserializer=world__pb2.SubscribeEventMessagesRequest.FromString,
                    response_serializer=world__pb2.SubscribeEntityResponse.SerializeToString,
            ),
            'UpdateEventMessagesSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEventMessagesSubscription,
                    request_deserializer=world__pb2.UpdateEventMessagesSubscriptionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeTokenBalances': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTokenBalances,
                    request_deserializer=world__pb2.RetrieveTokenBalancesRequest.FromString,
                    response_serializer=world__pb2.SubscribeTokenBalancesResponse.SerializeToString,
            ),
            'UpdateTokenBalancesSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTokenBalancesSubscription,
                    request_deserializer=world__pb2.UpdateTokenBalancesSubscriptionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeTokens': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTokens,
                    request_deserializer=world__pb2.RetrieveTokensRequest.FromString,
                    response_serializer=world__pb2.SubscribeTokensResponse.SerializeToString,
            ),
            'UpdateTokensSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTokensSubscription,
                    request_deserializer=world__pb2.UpdateTokenSubscriptionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RetrieveEventMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveEventMessages,
                    request_deserializer=world__pb2.RetrieveEventMessagesRequest.FromString,
                    response_serializer=world__pb2.RetrieveEntitiesResponse.SerializeToString,
            ),
            'RetrieveEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveEvents,
                    request_deserializer=world__pb2.RetrieveEventsRequest.FromString,
                    response_serializer=world__pb2.RetrieveEventsResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=world__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=world__pb2.SubscribeEventsResponse.SerializeToString,
            ),
            'RetrieveTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveTokens,
                    request_deserializer=world__pb2.RetrieveTokensRequest.FromString,
                    response_serializer=world__pb2.RetrieveTokensResponse.SerializeToString,
            ),
            'RetrieveTokenBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveTokenBalances,
                    request_deserializer=world__pb2.RetrieveTokenBalancesRequest.FromString,
                    response_serializer=world__pb2.RetrieveTokenBalancesResponse.SerializeToString,
            ),
            'RetrieveControllers': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveControllers,
                    request_deserializer=world__pb2.RetrieveControllersRequest.FromString,
                    response_serializer=world__pb2.RetrieveControllersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'world.World', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('world.World', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class World(object):
    """The World service provides information about the world.
    """

    @staticmethod
    def SubscribeIndexer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeIndexer',
            world__pb2.SubscribeIndexerRequest.SerializeToString,
            world__pb2.SubscribeIndexerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorldMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/WorldMetadata',
            world__pb2.WorldMetadataRequest.SerializeToString,
            world__pb2.WorldMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeModels',
            world__pb2.SubscribeModelsRequest.SerializeToString,
            world__pb2.SubscribeModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeEntities',
            world__pb2.SubscribeEntitiesRequest.SerializeToString,
            world__pb2.SubscribeEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntitiesSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/UpdateEntitiesSubscription',
            world__pb2.UpdateEntitiesSubscriptionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveEntities',
            world__pb2.RetrieveEntitiesRequest.SerializeToString,
            world__pb2.RetrieveEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveEntitiesStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/RetrieveEntitiesStreaming',
            world__pb2.RetrieveEntitiesRequest.SerializeToString,
            world__pb2.RetrieveEntitiesStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEventMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeEventMessages',
            world__pb2.SubscribeEventMessagesRequest.SerializeToString,
            world__pb2.SubscribeEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEventMessagesSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/UpdateEventMessagesSubscription',
            world__pb2.UpdateEventMessagesSubscriptionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTokenBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeTokenBalances',
            world__pb2.RetrieveTokenBalancesRequest.SerializeToString,
            world__pb2.SubscribeTokenBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTokenBalancesSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/UpdateTokenBalancesSubscription',
            world__pb2.UpdateTokenBalancesSubscriptionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeTokens',
            world__pb2.RetrieveTokensRequest.SerializeToString,
            world__pb2.SubscribeTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTokensSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/UpdateTokensSubscription',
            world__pb2.UpdateTokenSubscriptionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveEventMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveEventMessages',
            world__pb2.RetrieveEventMessagesRequest.SerializeToString,
            world__pb2.RetrieveEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveEvents',
            world__pb2.RetrieveEventsRequest.SerializeToString,
            world__pb2.RetrieveEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/world.World/SubscribeEvents',
            world__pb2.SubscribeEventsRequest.SerializeToString,
            world__pb2.SubscribeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveTokens',
            world__pb2.RetrieveTokensRequest.SerializeToString,
            world__pb2.RetrieveTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveTokenBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveTokenBalances',
            world__pb2.RetrieveTokenBalancesRequest.SerializeToString,
            world__pb2.RetrieveTokenBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveControllers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/world.World/RetrieveControllers',
            world__pb2.RetrieveControllersRequest.SerializeToString,
            world__pb2.RetrieveControllersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
